# -*- coding: utf-8 -*-
"""codesoft2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VUAG915Ia8tXbveD-vVqzzqrVOSbAJv
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))

    return password


try:
    length = int(input("Enter the desired password length: "))
    if length < 4:
        print("Password length should be at least 4 characters.")
    else:

        password = generate_password(length)
        print("Generated Password: ", password)
except ValueError:
    print("Please enter a valid number for the length.")